swagger: "2.0"
info:
  description: "Dantion Endpoints API."
  title: "Endpoints Dantion"
  version: "1.0.0"
host: "dantion.appspot.com"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
# Uncomment the next line if you configure SSL for this API.
- "https"
- "http"
paths:
  "/users":
    get:
      description: "Get All User"
      operationId: "getuser"
      produces:
      - "application/json"
      responses:
        200:
          description: "get all user"
          schema:
            $ref: "#/definitions/User"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      address:
        type: "string"
      number:
        type: "string"
      parentNumber:
        type: "string"
      password:
        type: "string"
        format: "password"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
  Detection:
    type: "object"
    properties:
      id:
        type: "string"
      lat:
        type: "number"
        format: "double"
      lon:
        type: "number"
        format: "double"
      recordUrl:
        type: "string"
        format: "binary"
      type:
        type: "string"
        enum:
        - "begal"
        - "kecelakaan"
      isValid:
        type: "boolean"
        default: false
      status:
        type: "string"
        description: "Danger Detection Status"
        enum:
        - "pelapor"
        - "korban"
      userId:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
  Place:
    type: "object"
    properties:
      id:
        type: "string"
      lat:
        type: "number"
        format: "double"
      lon:
        type: "number"
        format: "double"
      radius:
        type: "number"
        format: "double"
      type:
        type: "string"
        enum:
        - "begal"
        - "kecelakaan"
      isValid:
        type: "boolean"
        default: false
      status:
        type: "string"
        description: "Danger Detection Status"
        enum:
        - "pelapor"
        - "korban"
      userId:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
      updatedAt:
        type: "string"
        format: "date-time"
